version: '3'

services: 
  endpoint:
    build: ./src
    env_file: ./database.env
    volumes:
      - ./src:/usr/src/app
    ports:
        - 5000:80
    depends_on:
       -  database
  database:
    image: postgres
    restart: always
    env_file: ./database.env
    volumes:
      - ./data:/var/lib/postgresql/data