version: '3'

services: 
  endpoint:
    build: ./src
    env_file: ./test.env
    volumes:
      - ./src:/usr/src/app
    ports:
        - 5000:80
    depends_on:
       -  database
  database:
    image: postgres
    restart: always
    env_file: ./test.env 
  test:
    build: ./tests
    depends_on:
      - database
      - endpoint
    volumes:
      - ./tests:/usr/src/app
      - ./src:/usr/src/app/src_code
    env_file: ./test.env
