version: '3'

services: 
  endpoint:
    build: ./src
    restart: always
    env_file: ./database.env
    volumes:
      - ./src:/usr/src/app
    ports:
        - 5000:80
    depends_on:
       -  database
  database:
    image: postgres
    restart: always
    env_file: ./database.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5001:5432
  test:
    build: ./tests
    depends_on:
      - database
      - endpoint
    volumes:
      - ./tests:/usr/src/app
      - ./src:/usr/src/app/src-code
    command: ["./wait-for-it.sh", "endpoint:5000", "--timeout=30","--","pytest"]